project-feynman/explain-mit

- package-lock.json
- package.json
- src/components/VoiceChat.vue
- src/plugins/vuetify.js
- src/views/Workspace.vue
- yarn.lock
This PR implements P2P voice chat for connecting to an arbitrary number of peers in the same room. There is a known bug with an issue where duplicate connections can occur. Currently investigating.
> P2P Voice Chat

- package-lock.json
- package.json
- src/plugins/vuetify.js
- yarn.lock
Upgrades vuetify and fixes error messages when running `npm run serve`.
> Fix Build Errors

- src/App.vue
- src/components/BaseAppBar.vue
- src/components/HomeAppBar.vue
- src/components/PiazzaNewPost.vue
- src/components/PiazzaQuestionsList.vue
- src/components/PiazzaViewPost.vue
- src/views/Piazza.vue
Reverts eltonlin1998/ExplainMIT#20
There turns out to be some issues
> Revert "Q&A ui resizing across all devices"

- src/components/AudioRecorderMini.vue
- src/components/BlackboardMini.vue
- src/components/PiazzaNewPost.vue
- src/components/PiazzaViewPost.vue
- src/views/Piazza.vue
- Add mouse-drawing for Q&A
- Add (wonky) video-recording for Q&A 
- Fix lots of small bugs
> Fix piazza blackboard

- src/components/AudioRecorder.vue
- src/components/Blackboard.vue
- src/components/DoodleVideoAnimation.vue
- src/mixins/DrawMethods.js
- src/views/FullVideo.vue
This PR reworks the video playback algorithm to play frame-by-frame, allowing better syncing with audio, full drag support, and less CPU usage during playback. This also inherently fixes the bug with not being able to replay videos after a video ends.
> Frame-by-frame Video Playback

- functions/package-lock.json
- functions/package.json
- src/views/VideoGallery.vue
Fix video delete and update cloud functions.
> Fix Video Delete

- src/components/Blackboard.vue
- src/components/BlackboardMini.vue
- src/components/DoodleVideoAnimation.vue
- src/mixins/DrawMethods.js
- src/views/FullVideo.vue
Window resize on video replays now work correctly.
> Fix Window Resizing on Videos

- src/components/Blackboard.vue
- src/components/BlackboardToolBar.vue
- src/components/TheAppBar.vue
- src/views/BlackboardRoom.vue
Realtime blackboard fills all the space available. The drawing should have no offset.
> Blackboard resize

- src/App.vue
- src/CONSTANTS.js
- src/components/Blackboard.vue
- src/components/BlackboardToolBar.vue
- src/components/ButtonNew.vue
- src/components/TheAppBar.vue
- src/pages/Home.vue
New button should be compatible
> New button

- src/components/TextEditor.vue
> placeholder 

- src/components/Blackboard.vue
- src/mixins/CanvasDrawMixin.js
- Stroke eraser is now additive
- Background doesn't disappear when stroke is erased
> Stroke eraser

- src/components/DoodleAnimation.vue
- src/components/DoodleVideo.vue
- src/mixins/CanvasDrawMixin.js
Currently I have pulled the animation throttling down to 10 frames per second. If it still lags, we can get it lower than that
> Animation Throttling

- package-lock.json
- src/CONSTANTS.js
- src/components/Blackboard.vue
- src/components/BlackboardDrawingCanvas.vue
- src/components/BlackboardToolBar.vue
- src/components/CreateExplanation.vue
- src/components/FullScreenDialog.vue
- src/mixins/CanvasDrawMixin.js
- src/pages/ClassPageLiveBoard.vue
The blackboard toolbar is not reacting to the changes to its props. This is causing the icons in the toolbar to not properly display the current state of the tools and fullscreen.
> Fullscreen blackboard

- src/components/Blackboard.vue
- src/components/CreateExplanation.vue
- src/mixins/DatabaseHelpersMixin.js
- src/pages/ClassPageNewPost.vue
- src/pages/ClassPageSeePost.vue
Fixed consecutive posts overwriting; Better error handling for video upload; Pressing "retry recording" will fully reset the board
> Fix Professor's bugs

- src/components/CreateExplanation.vue
- src/mixins/DatabaseHelpersMixin.js
Does firestore upload API give feature to catch errors instead of setting timeout?
> Uploading progress bar

- functions/index.js
- src/CONSTANTS.js
- src/components/CreateExplanation.vue
- src/components/MenuEmailSettings.vue
- src/components/SeeExplanation.vue
- src/components/TheAppBar.vue
- src/components/TheDropdownMenu.vue
- src/components/TheSideDrawer.vue
- src/pages/ClassPage.vue
- src/pages/ClassPageOverview.vue
- src/pages/Home.vue
- src/store.js
- Redesigned email options. 
- Users now have sensible email defaults (`emailOnNewReply` and `emailWeeklySummary` are on, `emailOnNewPost` and `emailDailySummary` are off).
- UI improvements e.g. email now displays the blackboard images
> Redesigned email system

- src/components/CreateExplanation.vue
The bug with previewing doodlevideo should be fixed
> doodle in create explanation

- src/CONSTANTS.js
- src/components/BasePopupButton.vue
- src/components/Blackboard.vue
- src/components/ButtonNew.vue
- src/components/CreateExplanation.vue
- src/components/FileExplorer.vue
- src/components/MenuEmailSettings.vue
- src/components/SeeExplanation.vue
- src/components/TextEditor.vue
- src/components/TheAppBar.vue
- src/components/TheDropdownMenu.vue
- src/components/TheSearchBar.vue
- src/components/TheSideDrawer.vue
- src/mixins/AuthHelpers.js
- src/mixins/DatabaseHelpersMixin.js
- src/pages/ClassPage.vue
- src/pages/ClassPageNewPost.vue
- src/pages/ClassPageOverview.vue
- src/pages/ClassPageSeePost.vue
- src/pages/Home.vue
- src/store.js
Major changes include:
- Redesign the home page to showcase Doodle components and the Blackboard better
- Allow non-logged-in users to explore around classes
- Explicit title inputs for new posts
See full detail below: https://explain.mit.edu/class/mDbUrvjy4pe8Q5s5wyoD/posts/BAsIFjHy4tfepC1x2RiD
> Home redesign; Let users explore without logging in; Explicit titles

- src/components/CreateExplanation.vue
- src/components/DoodleAnimation.vue
- src/components/DoodleVideo.vue
- src/components/SeeExplanation.vue
- src/mixins/DoodleFullscreenMixin.js
- src/styles/doodle-fullscreen.scss
-added mixin for fullscreen functions
-added css file for fullscreen css
-contained fullscreen logic in doodleVideo and doodleAnimation
> Consolidated fullscreen logic for doodle

- src/CONSTANTS.js
- src/pages/ClassPageLiveBoard.vue
- src/pages/Home.vue
Previously, we use technical keywords to describe the platfrom "An efficient, blackboard-centric explanation platfrom handcrafted for MIT classes". 
However, I want to try something different. I want to try to create a vision of the project, the original vision 2 years ago, and have that be illustrated by the home description. It's now "A vibrant place where students, TAs and professors explain things to each other."
> Update the home page

- src/components/RoomExplorer.vue
- Physics specific room categories, should be able to integrate actual db structure with this UI later.
> added roomCategories with expansion panels

- src/components/LiveBoardAudio.vue
- src/components/RoomExplorer.vue
-Join Audio Button before connected
-loading spinner while connecting
> added 'join audio' btn with loading spinner

- functions/index.js
- src/components/RoomExplorer.vue
- src/pages/ClassPageCenterTable.vue
- added db structure for room types
- randomization for groups can now be selected by room type and group size
- disconnect logic for users in main lobby should be better (disconnect hook and on destroy leave the room)
> Rooms categories 2

- .gitignore
- functions/index.js
- src/components/CreateExplanation.vue
- src/components/MenuEmailSettings.vue
- src/mixins/ExplUploadHelpers.js
- Email notifications work for on new question and on new reply
> email notifs work for questions

- .gitignore
- functions/index.js
- package-lock.json
- package.json
- src/components/LiveBoardAudio.vue
- src/components/RoomExplorer.vue
- src/main.js
- src/pages/ClassPageLiveBoard.vue
- got video chat working
- refactored logic for media control a bit
- refactored roomParticipant structure: now uses a collection of participants for each room
> Video chat

- src/components/CreateBlackboardPopup.vue
- src/components/RoomExplorer.vue
- src/pages/Home.vue
- can create rooms and room types
- when creating a class, a default room type is created named Blackboard Rooms
> finished room creation

- package-lock.json
- src/components/LiveBoardAudio.vue
- src/pages/ClassPageCenterTable.vue
- src/pages/ClassPageLiveBoard.vue
- src/plugins/vuetify.js
- more CSS
- put video display at top
- refactored portals for each user to single portal
- cleaned up some listener not being removed in Main Lobby, and cancel firebase disconnect hooks on destroy
> Live video improvements

- functions/index.js
- src/pages/ClassPageCenterTable.vue
- src/pages/ClassPageLiveBoard.vue
- got MainLobby Randomization working.
- more cleanup for connect hook. Now removes connect hook on destroy
> Participants fixes

- .gitignore
- functions/index.js
- functions/package-lock.json
- functions/package.json
- package-lock.json
- package.json
- src/components/FileExplorerByDate.vue
- src/components/PostSearch.vue
- text search works 
- UI display needs to be improved but works for now
> Algolia text search

- src/components/RealtimeAudio.vue
- src/components/RealtimeMessageChat.vue
- src/pages/ClassPageLectureHall.vue
- src/pages/ClassPageRealtimeSpace.vue
- added function that iterates to next tick until video container is found so that tracks can be added. Was already using concept for video view switch but not for initializing connection. Should hopefully improve reliability
> Media track reliability

- src/pages/ClassPageRealtimeSpace.vue
-Uses Firebase to send a signal to all rooms in the roomCategory of which room to move to.
- All participants in a roomCategory are moved to the room from which the button was clicked
> Force students back

- package-lock.json
- package.json
- src/components/BlackboardCoreDrawing.vue
- src/components/RealtimeBlackboard.vue
Works for realtime blackboard, but for async blackboards, even uploading image doesn't work
> import pdf and convert to image

- src/components/RealtimeSpaceTwilioRoom.vue
- src/components/TheSideDrawerSpaces.vue
- src/store.js
Also removes global `twilioRoom` state. `twilioRoom` is now self contained to `RealtimeSpaceTwilioRoom.vue`.
The feature is implemented using Firebase firestore and a counter that increments every time that someone initiates a muteAll.
> Add mute all feature

- src/components/TheSideDrawerSpaces.vue
After shuffling, each room has at least minRoomSizeOnShuffle people.
> Fix breakout bugs + redo algorithm + delete old code

- src/components/TheSideDrawerSpaces.vue
- src/pages/RealtimeSpace.vue
> Fix announcements

- src/components/Blackboard.vue
- src/components/BlackboardCoreDrawing.vue
- src/components/BlackboardToolBar.vue
- src/components/ClassPageSeePost.vue
- src/components/RealtimeBlackboard.vue
- src/components/RealtimeSpaceTwilioRoom.vue
- src/components/TheSideDrawerBeta.vue
- src/components/TheSideDrawerSpaces.vue
- src/mixins/ExplUploadHelpers.js
- src/pages/ClassPage.vue
- src/pages/ClassPageOverview.vue
- src/pages/RealtimeSpace.vue
- src/store.js
> Final redesign

- src/components/TheSideDrawerGroupByDate.vue
But we still see the ~~animated~~ loading of weeks
> promise all

- src/components/PresentationalRoomUI3.vue
- src/components/RealtimeSpaceTwilioRoom.vue
- src/components/TheSideDrawerSpaces2.vue
- src/pages/RealtimeSpace.vue
On shuffle, all people with the same session id are considered as one person and get placed in the same room.
> Use session ids

- functions/index.js
- src/App.vue
- src/CONSTANTS.js
- src/components/Blackboard.vue
- src/components/BlackboardCoreDrawing.vue
- src/components/BlackboardToolBar.vue
- src/components/BlackboardToolBarPenSwatch.vue
- src/components/DoodleAnimation.vue
- src/components/DoodleVideo.vue
- src/components/ExplanationCreate.vue
- src/components/HandleUpdatingParticipants.vue
- src/components/RealtimeBlackboard.vue
- src/components/TheSideDrawerGroupByDate.vue
- src/components/VideoConferenceRoom.vue
- src/helpers.js
- src/mixins/ExplUploadHelpers.js
- src/pages/ClassPageLayout.vue
- src/pages/RealtimeRoom.vue
- src/store.js
Changes include: 
- Everyone can explore and keep their favorite colors
- Board numbers are colored to reflect which the pen color of each participant
- Undo button, large eraser and small eraser
- Fix critical bugs for the library
> Blackboard upgrade

- src/App.vue
- src/components/ClassSwitchDropdown.vue
- src/components/DoodleAnimation.vue
- src/components/DoodleVideo.vue
- src/components/ExplanationCreate.vue
- src/components/MyParticipantDocUpdater.vue
- src/components/VideoConferenceRoom.vue
- src/components/VisualForum.vue
- src/pages/AllOpenSpaces.vue
- src/pages/ClassPageLayout.vue
- src/pages/ParticularOpenSpace.vue
- src/pages/RealtimeRoom.vue
- src/store.js
Including fix for Daily Ghosts
> Personal library and pioneer icons

- src/components/ArmyOfHelpers.vue
- src/components/ExplanationDisplay.vue
- src/components/ExplanationGroupDisplay.vue
- src/components/MapleMusicPlayer.vue
- src/pages/ClassLibrary.vue
- src/pages/ClassPageLayout.vue
> Army of helpers
